[package]
name = "off-chain-agent"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
axum = "0.7.4"
candid = "0.10.3"
chrono = { version = "0.4.34", features = ["serde"] }
futures = "0.3.30"
ic-agent = "0.33.0"
rust-s3 = "0.33.0"
serde = "1.0.197"
serde_json = "1.0.114"
stringreader = "0.1.1"
tokio = { version = "1.36.0", features = ["macros", "rt-multi-thread", "time"] }
openssl = { version = "0.10", features = ["vendored"] }
axum-auth = { version = "0.7", default-features = false, features = [
    "auth-bearer",
] }
indicatif = { version = "0.17.8", features = ["futures"] }

[[bin]]
name = "icp-off-chain-agent"
path = "src/main.rs"
