[package]
name = "off-chain-agent"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
axum = { version = "0.6.20", features = ["macros"] }
candid = "0.10.3"
chrono = { version = "0.4.34", features = ["serde"] }
futures = "0.3.30"
ic-agent = "0.33.0"
rust-s3 = "0.33.0"
serde = "1.0.197"
serde_json = "1.0.114"
stringreader = "0.1.1"
tokio = { version = "1.36.0", features = ["macros", "rt-multi-thread", "time"] }
openssl = { version = "0.10", features = ["vendored"] }
indicatif = { version = "0.17.8", features = ["futures"] }
tonic = { version = "0.11.0", features = ["tls-roots"] }
prost = "0.12.4"
tower = { version = "0.4", features = ["full"] }
hyper = { version = "0.14.26", features = ["full"] }
http = "0.2.11"
axum-extra = { version = "0.9.3", features = ["typed-header"] }
headers = "0.4.0"
tonic-reflection = "0.11.0"
reqwest = { version = "0.12.3", features = ["json"] }
once_cell = "1.19.0"
yup-oauth2 = "8.3.3"
tonic-web = "0.11.0"

[build-dependencies]
tonic-build = "0.11"

[[bin]]
name = "icp-off-chain-agent"
path = "src/main.rs"
