name: Build and Check linting

on:
  workflow_call:
    inputs:
      publish-artifact:
        default: false
        required: false
        type: boolean
  workflow_dispatch:
  pull_request:
    branches:
      - main

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    permissions:
      id-token: write
      contents: read
          
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository and submodules
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - id: 'auth'
        name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v1'
        with:
          create_credentials_file: true
          workload_identity_provider: 'projects/82502260393/locations/global/workloadIdentityPools/yral-id-pool/providers/yral-provider'
          service_account: 'yral-srv-workload@hot-or-not-feed-intelligence.iam.gserviceaccount.com'

      - name: Test file path
        run: |
          cat ${{ steps.auth.outputs.credentials_file_path }}
      - name: Read file contents and set as output
        id: read_workload_credentials
        run: |
          echo "::set-output name=file_content::$(cat ${{ steps.auth.outputs.credentials_file_path }})"
      - name: Test file
        run: |
          cat ${{ steps.read_workload_credentials.outputs.file_content }}

      - name: Install prereqs
        run: |
          sudo apt-get install protobuf-compiler
      - name: Build setup
        run: |
          pip3 install ziglang
          cargo install cargo-zigbuild
          rustup target add x86_64-unknown-linux-musl
          rustup component add rustfmt
          rustup component add clippy
      # - name: lint check
      #   run: |
      #     cargo fmt --check
      #     cargo clippy --no-deps --all-features --release -- -Dwarnings
      - name: Build
        run: cargo zigbuild --release --target x86_64-unknown-linux-musl
      # - name: Run tests
      #   run: cargo test --verbose
      - run: touch .empty
      - name: Archive production artifacts
        uses: actions/upload-artifact@v4
        if: ${{ inputs.publish-artifact }}
        with:
          name: build-musl
          path: |
            target/x86_64-unknown-linux-musl/release/icp-off-chain-agent
            .empty
