name: Deploy to Fly on push to main
on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build_check:
    uses: ./.github/workflows/build-check.yml
    with:
      publish-artifact: true

  deploy:
    name: Deploy
    needs: build_check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Download build
        uses: actions/download-artifact@v4
        with:
          name: build-musl
      - run: chmod +x target/x86_64-unknown-linux-musl/release/icp-off-chain-agent
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - name: Set cloudflare token
        run: flyctl secrets set CF_R2_ACCESS_KEY_TEMP=$CF_R2_ACCESS_KEY_TEMP CF_R2_SECRET_ACCESS_KEY_TEMP=$CF_R2_SECRET_ACCESS_KEY_TEMP CF_WORKER_ACCESS_OFF_CHAIN_AGENT_KEY=$CF_WORKER_ACCESS_OFF_CHAIN_AGENT_KEY RECLAIM_CANISTER_PEM=$RECLAIM_CANISTER_PEM HOTORNOT_CF_ACCOUNT_ID=$HOTORNOT_CF_ACCOUNT_ID --app "icp-off-chain-agent" --stage
        env:
          FLY_API_TOKEN: ${{ secrets.TEMP_HOT_OR_NOT_OFF_CHAIN_AGENT_FLY_IO_GITHUB_ACTION }}
          CF_R2_ACCESS_KEY_TEMP: ${{ secrets.CF_R2_ACCESS_KEY_TEMP }}
          CF_R2_SECRET_ACCESS_KEY_TEMP: ${{ secrets.CF_R2_SECRET_ACCESS_KEY_TEMP }}
          CF_WORKER_ACCESS_OFF_CHAIN_AGENT_KEY: ${{ secrets.CF_WORKER_ACCESS_OFF_CHAIN_AGENT_KEY }}
          RECLAIM_CANISTER_PEM: ${{ secrets.RECLAIM_CANISTER_PEM }}
          HOTORNOT_CF_ACCOUNT_ID: ${{ secrets.HOTORNOT_CF_ACCOUNT_ID }}
      - name: Deploy a docker container to fly.io
        run: flyctl deploy --remote-only
        env:
          FLY_API_TOKEN: ${{ secrets.TEMP_HOT_OR_NOT_OFF_CHAIN_AGENT_FLY_IO_GITHUB_ACTION }}
